---
- name: Lookup installed versions
  continuouscloud.dotnet.win_dotnet_core_info:
    type: "{{ dotnet_core_type }}"
    version: "{{ dotnet_core_version | first }}"
  register: _dotnet_info

- name: Install Dotnet Core
  ansible.builtin.include_tasks: install.yml
  when: >-
    not _latest_installed_version or
    _latest_installed_version is version(_expected_version, '<') or
    (_expected_components | difference(_latest_installed_components) | length > 0)
  vars:
    _latest_installed_version: "{{ _dotnet_info[dotnet_core_type].versions[0] | default('') }}"
    _latest_installed_components: "{{ _dotnet_info[dotnet_core_type].components[_latest_installed_version] | default([]) }}"
    _expected_version: "{{ __dotnet_core_install_vars.full_version }}"
    _expected_components: >-
      {{ __dotnet_core_install_vars.expected_components | default(dotnet_core_vars[dotnet_core_type].expected_components) }}
